# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    # ARM_ACCESS_KEY
    
  }
  required_providers {
    azurerm = {
     
      source  = "hashicorp/azurerm"
      version = "~> 2.12"
    }
  }
  
}

provider "azurerm" { 
    features {}
}
